"""Language bridges: how C/C++, Swift, Kotlin/Java and Python call an HA++ library.

  include/<name>.h + module.modulemap   C, C++, Objective-C, Swift
  android/kotlin, android/java          Kotlin / Java (JNI glue is already inside the .so)
  apple/<Class>/                        Swift package: <Class>Core.xcframework (made without
                                        Xcode) + Swift wrapper that runs the kernels with Metal
  python/<name>.py                      ctypes bindings for PC tools and AI experiments
"""

import os
import plistlib
import shutil
import subprocess

from . import __version__
from . import types as T
from .errors import HappError
from .gpu import kernel_layout

C_SCALAR = {"bool": "bool", "i8": "int8_t", "u8": "uint8_t", "i16": "int16_t", "u16": "uint16_t",
            "i32": "int32_t", "u32": "uint32_t", "i64": "int64_t", "u64": "uint64_t",
            "f16": "ha_f16", "f32": "float", "f64": "double"}
KT_SCALAR = {"bool": "Boolean", "i8": "Byte", "u8": "Byte", "i16": "Short", "u16": "Short", "i32": "Int",
             "u32": "Int", "i64": "Long", "u64": "Long", "f32": "Float", "f64": "Double"}
JAVA_SCALAR = {"bool": "boolean", "i8": "byte", "u8": "byte", "i16": "short", "u16": "short", "i32": "int",
               "u32": "int", "i64": "long", "u64": "long", "f32": "float", "f64": "double"}
KT_ARRAY = {"bool": "BooleanArray", "i8": "ByteArray", "u8": "ByteArray", "i16": "ShortArray",
            "u16": "ShortArray", "f16": "ShortArray", "i32": "IntArray", "u32": "IntArray",
            "i64": "LongArray", "u64": "LongArray", "f32": "FloatArray", "f64": "DoubleArray"}
JAVA_ARRAY = {"bool": "boolean[]", "i8": "byte[]", "u8": "byte[]", "i16": "short[]", "u16": "short[]",
              "f16": "short[]", "i32": "int[]", "u32": "int[]", "i64": "long[]", "u64": "long[]",
              "f32": "float[]", "f64": "double[]"}
PY_CTYPE = {"bool": "ctypes.c_bool", "i8": "ctypes.c_int8", "u8": "ctypes.c_uint8", "i16": "ctypes.c_int16",
            "u16": "ctypes.c_uint16", "f16": "ctypes.c_uint16", "i32": "ctypes.c_int32",
            "u32": "ctypes.c_uint32", "i64": "ctypes.c_int64", "u64": "ctypes.c_uint64",
            "f32": "ctypes.c_float", "f64": "ctypes.c_double"}


def header_banner(src, comment="//"):
    return f"{comment} Generated by HA++ {__version__} from {src}. Do not edit: change the .ha file and rebuild."


def cpu_kernels(prog):
    return list(prog.cpu_kernels)


# ====================================================================== C header

class CHeader:
    def __init__(self, prog):
        self.prog = prog
        self.vec_types = set()

    def ctype(self, t):
        if t.is_scalar:
            return C_SCALAR[t.name]
        if t.is_vec:
            self.vec_types.add(t)
            return f"ha_{t}"
        if t.is_mat:
            self.vec_types.add(t)
            return f"ha_{t}"
        if t.is_ptr:
            if t.pointee.is_array:
                return "void *"
            return f"{self.ctype(t.pointee)} *"
        if t.is_struct:
            return t.name
        if t.is_void:
            return "void"
        raise TypeError(t)

    def field(self, name, t):
        dims = ""
        while t.is_array:
            dims += f"[{t.n}]"
            t = t.elem
        return f"{self.ctype(t)} {name}{dims}"

    def param(self, p):
        ct = self.ctype(p.ty)
        return f"{ct}{'' if ct.endswith('*') else ' '}{p.name}"

    def render(self, name, src, spirv_kernels, has_metal, gpu_runtime):
        prog = self.prog
        body = []
        # declare every struct name first: a field can point to its own struct or to one defined later
        for st in prog.structs:
            body.append(f"typedef struct {st.name} {st.name};")
        if prog.structs:
            body.append("")
        for st in prog.structs:
            size, _ = T.size_align(st)
            body.append(f"struct {st.name} {{")
            for fname, ft in st.fields:
                body.append(f"    {self.field(fname, ft)};")
            body.append("};")
            body.append(f"HA_ASSERT_SIZE({st.name}, {size});")
            body.append("")
        if prog.exports:
            body.append("/* ---- exported functions ---- */")
            for fn in prog.exports:
                params = ", ".join(self.param(p) for p in fn.params) or "void"
                body.append(f"HA_API {self.ctype(fn.ret_ty)} {fn.name}({params});")
            body.append("")
        for k in prog.kernels:
            buffers, scalars = kernel_layout(k)
            wg = k.sig["workgroup"]
            up = k.name.upper()
            body.append(f"/* ---- kernel {k.name}: buffers "
                        f"{', '.join(f'{i}={p.name}' for i, p in enumerate(buffers)) or 'none'} ---- */")
            body.append(f"#define HA_{up}_WORKGROUP_X {wg[0]}")
            body.append(f"#define HA_{up}_WORKGROUP_Y {wg[1]}")
            body.append(f"#define HA_{up}_WORKGROUP_Z {wg[2]}")
            body.append(f"#define HA_{up}_BUFFERS {len(buffers)}")
            if scalars:
                fields = " ".join(f"{self.ctype(p.ty)} {p.name};" for p in scalars)
                body.append(f"/* push constants (Vulkan) / [[buffer({len(buffers)})]] (Metal) */")
                body.append(f"typedef struct ha_params_{k.name} {{ {fields} }} ha_params_{k.name};")
            if k in cpu_kernels(prog):
                params = [self.param(p) for p in k.params] + ["uint32_t groups_x", "uint32_t groups_y",
                                                              "uint32_t groups_z"]
                body.append("/* the same kernel on the CPU (all groups, one thread) */")
                body.append(f"HA_API void {k.name}_cpu({', '.join(params)});")
            if k.name in spirv_kernels:
                body.append("/* SPIR-V for Vulkan, embedded in Android/Windows/Linux builds */")
                body.append(f"HA_API const void *{name}_spirv_{k.name}(uint64_t *size);")
            body.append("")
        if has_metal:
            body.append("/* Metal source of all kernels, embedded in iOS/macOS builds (compile with")
            body.append("   MTLDevice.makeLibrary(source:)); NULL-terminated */")
            body.append(f"HA_API const char *{name}_metal_source(uint64_t *size);")
            body.append("")
        vec_defs = []
        for t in sorted(self.vec_types, key=str):
            if t.is_vec:
                et = C_SCALAR[t.elem.name]
                comps = ", ".join("xyzw"[:t.n])
                vec_defs.append(f"typedef struct ha_{t} {{ {et} {comps}; }} ha_{t};")
            else:
                vec_defs.append(f"typedef struct ha_{t} {{ float m[{t.n * t.n}]; }} ha_{t}; /* column-major */")
        guard = f"HA_{name.upper()}_H"
        lines = [f"/* {header_banner(src, '').strip()} */",
                 f"#ifndef {guard}", f"#define {guard}",
                 "#include <stdbool.h>", "#include <stddef.h>", "#include <stdint.h>",
                 "#ifdef __cplusplus", 'extern "C" {', "#endif", "",
                 "#if defined(_WIN32) && !defined(HA_STATIC)",
                 "#define HA_API __declspec(dllimport)", "#else", "#define HA_API", "#endif",
                 "#ifdef __cplusplus",
                 "#define HA_ASSERT_SIZE(T, n) static_assert(sizeof(T) == (n), \"HA++ layout of \" #T)",
                 "#else",
                 "#define HA_ASSERT_SIZE(T, n) _Static_assert(sizeof(T) == (n), \"HA++ layout of \" #T)",
                 "#endif", "",
                 "/* HA++ memory layout = C layout; vectors are tightly packed (vec3 = 12 bytes). */",
                 "typedef uint16_t ha_f16; /* IEEE half-precision bits */"]
        lines += vec_defs + [""] + body
        if gpu_runtime:
            lines += ["/* GPU runtime (Vulkan) is linked into Android/Windows/Linux builds: see ha_gpu.h */", ""]
        lines += ["#ifdef __cplusplus", "}", "#endif", "#endif", ""]
        return "\n".join(lines)


# ====================================================================== Kotlin / Java

def jvm_param(p_ty, lang):
    t = p_ty
    if t.is_ptr:
        pte = t.pointee
        if pte.is_scalar:
            return (KT_ARRAY if lang == "kt" else JAVA_ARRAY)[pte.name]
        return "java.nio.ByteBuffer"
    return (KT_SCALAR if lang == "kt" else JAVA_SCALAR)[t.name]


def jvm_ret(t, lang):
    if t.is_void:
        return "Unit" if lang == "kt" else "void"
    if t.is_ptr:
        return "Long" if lang == "kt" else "long"
    return (KT_SCALAR if lang == "kt" else JAVA_SCALAR)[t.name]


def jvm_methods(prog, spirv_kernels, gpu_runtime):
    """(name, [(param, kt, java)], (kt_ret, java_ret), doc) for every JNI method in the library."""
    ms = []
    for fn in prog.exports:
        ps = [(p.name, jvm_param(p.ty, "kt"), jvm_param(p.ty, "java")) for p in fn.params]
        ms.append((fn.name, ps, (jvm_ret(fn.ret_ty, "kt"), jvm_ret(fn.ret_ty, "java")), None))
    for k in cpu_kernels(prog):
        ps = [(p.name, jvm_param(p.ty, "kt"), jvm_param(p.ty, "java")) for p in k.params]
        ps += [("groupsX", "Int", "int"), ("groupsY", "Int", "int"), ("groupsZ", "Int", "int")]
        ms.append((f"{k.name}_cpu", ps, ("Unit", "void"), f"kernel '{k.name}' on the CPU"))
    if gpu_runtime:
        L, I, Z = ("Long", "long"), ("Int", "int"), ("Boolean", "boolean")

        def m(name, params, ret, doc=None):
            ms.append((name, [(n, t[0], t[1]) for n, t in params], ret, doc))

        m("gpuCreate", [], L, "Vulkan GPU context (0 if Vulkan is unavailable)")
        m("gpuDestroy", [("gpu", L)], ("Unit", "void"))
        m("gpuName", [("gpu", L)], ("String", "String"))
        m("gpuHasF16", [("gpu", L)], Z)
        m("bufferCreate", [("gpu", L), ("bytes", L)], L, "GPU buffer the CPU can read and write")
        m("bufferData", [("buffer", L)], ("java.nio.ByteBuffer", "java.nio.ByteBuffer"),
          "direct view of the buffer memory (set .order(ByteOrder.nativeOrder()))")
        m("bufferDestroy", [("buffer", L)], ("Unit", "void"))
        m("kernelDestroy", [("kernel", L)], ("Unit", "void"))
        m("batchBegin", [("gpu", L)], I, "record several kernel runs (xxxRecord) ...")
        m("batchSubmit", [("gpu", L)], I, "... then run them all and wait")
        for k in prog.kernels:
            if k.name not in spirv_kernels:
                continue
            buffers, scalars = kernel_layout(k)
            wg = k.sig["workgroup"]
            m(f"{k.name}Kernel", [("gpu", L)], L, f"create kernel '{k.name}' (workgroup {wg[0]}x{wg[1]}x{wg[2]})")
            ps = [("gpu", L), ("kernel", L)] + [(p.name, L) for p in buffers]
            ps += [(p.name, ("Float", "float") if p.ty.is_float else I) for p in scalars]
            ps += [("groupsX", I), ("groupsY", I), ("groupsZ", I)]
            m(f"{k.name}Run", ps, I, f"run '{k.name}' and wait; buffers are bufferCreate() handles")
            m(f"{k.name}Record", ps, I, f"add '{k.name}' to the current batch")
    return ms


def layout_constants(prog):
    """Kotlin/Java constants: SIZEOF_<STRUCT>, OFFSET_<STRUCT>_<FIELD>, WORKGROUP_<KERNEL>_X.
    The prefixes keep the three kinds apart; a clash inside one kind is reported."""
    out = []
    for st in prog.structs:
        size, _ = T.size_align(st)
        out.append((f"SIZEOF_{st.name.upper()}", size, f"struct {st.name}", st.loc))
        for (fname, _), off in zip(st.fields, T.field_offsets(st)):
            out.append((f"OFFSET_{st.name.upper()}_{fname.upper()}", off, f"field {st.name}.{fname}", st.loc))
    for k in prog.kernels:
        wg = k.sig["workgroup"]
        for axis, v in zip("XYZ", wg):
            out.append((f"WORKGROUP_{k.name.upper()}_{axis}", v, f"kernel {k.name}", k.loc))
    seen = {}
    for cname, _, what, loc in out:
        if cname in seen and seen[cname] != what:
            raise HappError(f"{what} and {seen[cname]} both give the Kotlin/Java constant {cname}",
                            loc, "rename one of them")
        seen[cname] = what
    return [(cname, v) for cname, v, _, _ in out]


def check_kernel_names(prog):
    """The C header names kernels in upper case (HA_<KERNEL>_BUFFERS...): 'blur' and 'Blur' would clash."""
    seen = {}
    for k in prog.kernels:
        up = k.name.upper()
        if up in seen:
            raise HappError(f"kernels '{seen[up]}' and '{k.name}' differ only in upper/lower case; "
                            f"generated C/Kotlin/Java names would clash", k.loc, "rename one of them")
        seen[up] = k.name


def render_kotlin(prog, src, name, package, cls, spirv_kernels, gpu_runtime):
    lines = [header_banner(src), f"package {package}", "",
             f"/** Native functions from lib{name}.so (HA++). Struct sizes and field offsets are the",
             " *  constants below; use ByteBuffer.order(ByteOrder.nativeOrder()) to fill buffers. */",
             f"object {cls} {{", f'    init {{ System.loadLibrary("{name}") }}', ""]
    for cname, v in layout_constants(prog):
        lines.append(f"    const val {cname} = {v}")
    if layout_constants(prog):
        lines.append("")
    for mname, ps, (kret, _), doc in jvm_methods(prog, spirv_kernels, gpu_runtime):
        if doc:
            lines.append(f"    /** {doc} */")
        params = ", ".join(f"{p}: {kt}" for p, kt, _ in ps)
        ret = "" if kret == "Unit" else f": {kret}"
        lines.append(f"    @JvmStatic external fun {mname}({params}){ret}")
    lines += ["}", ""]
    return "\n".join(lines)


def render_java(prog, src, name, package, cls, spirv_kernels, gpu_runtime):
    lines = [header_banner(src), f"package {package};", "",
             f"/** Native functions from lib{name}.so (HA++). */",
             f"public final class {cls} {{", f'    static {{ System.loadLibrary("{name}"); }}', "",
             f"    private {cls}() {{}}", ""]
    for cname, v in layout_constants(prog):
        lines.append(f"    public static final int {cname} = {v};")
    lines.append("")
    for mname, ps, (_, jret), doc in jvm_methods(prog, spirv_kernels, gpu_runtime):
        if doc:
            lines.append(f"    /** {doc} */")
        params = ", ".join(f"{jt} {p}" for p, _, jt in ps)
        lines.append(f"    public static native {jret} {mname}({params});")
    lines += ["}", ""]
    return "\n".join(lines)


# ====================================================================== Swift (Apple)

SWIFT_SCALAR = {"bool": "Bool", "i8": "Int8", "u8": "UInt8", "i16": "Int16", "u16": "UInt16", "i32": "Int32",
                "u32": "UInt32", "i64": "Int64", "u64": "UInt64", "f32": "Float", "f64": "Double"}


def render_swift(prog, src, name, cls):
    lines = [header_banner(src), "// Swift wrapper: C functions come from the C module; kernels run with Metal.",
             "// (Generated code. Not compiled on the build machine: no Swift/Metal toolchain there.)",
             f"@_exported import {cls}Core", ""]
    if not prog.kernels:
        return "\n".join(lines) + "\n"
    lines += ["#if canImport(Metal)", "import Metal", "",
              f"public enum {cls}GPUError: Error {{ case noDevice, noQueue, missingKernel(String) }}", "",
              f"/// Runs the kernels of {src} on the GPU with Metal. Buffers use the HA++ layout,",
              "/// so the C structs from the header describe their contents.",
              f"public final class {cls}GPU {{",
              "    public let device: MTLDevice",
              "    public let queue: MTLCommandQueue",
              "    public let library: MTLLibrary",
              "    private var pipelines: [String: MTLComputePipelineState] = [:]", "",
              "    public init(device: MTLDevice) throws {",
              "        self.device = device",
              f"        guard let q = device.makeCommandQueue() else {{ throw {cls}GPUError.noQueue }}",
              "        queue = q",
              "        var size: UInt64 = 0",
              f"        let source = String(cString: {name}_metal_source(&size))",
              "        library = try device.makeLibrary(source: source, options: nil)",
              "    }", "",
              "    public convenience init() throws {",
              f"        guard let d = MTLCreateSystemDefaultDevice() else {{ throw {cls}GPUError.noDevice }}",
              "        try self.init(device: d)",
              "    }", "",
              "    /// Shared CPU/GPU memory (the fast path on iPhone).",
              "    public func makeBuffer(bytes: Int) -> MTLBuffer? {",
              "        device.makeBuffer(length: max(bytes, 4), options: .storageModeShared)",
              "    }", "",
              "    public func pipeline(_ name: String) throws -> MTLComputePipelineState {",
              "        if let p = pipelines[name] { return p }",
              f"        guard let f = library.makeFunction(name: name) else {{ throw {cls}GPUError.missingKernel(name) }}",
              "        let p = try device.makeComputePipelineState(function: f)",
              "        pipelines[name] = p",
              "        return p",
              "    }", "",
              "    /// Run `encode` in one command buffer and wait for the GPU.",
              "    public func run(_ encode: (MTLComputeCommandEncoder) throws -> Void) throws {",
              "        guard let cmd = queue.makeCommandBuffer(), let enc = cmd.makeComputeCommandEncoder() else {",
              f"            throw {cls}GPUError.noQueue",
              "        }",
              "        try encode(enc)",
              "        enc.endEncoding()",
              "        cmd.commit()",
              "        cmd.waitUntilCompleted()",
              "    }", ""]
    for k in prog.kernels:
        buffers, scalars = kernel_layout(k)
        wg = k.sig["workgroup"]
        args = [f"{p.name}: MTLBuffer" for p in buffers]
        args += [f"{p.name}: {SWIFT_SCALAR[p.ty.name]}" for p in scalars]
        args += ["groups: MTLSize"]
        lines += [f"    /// kernel {k.name}: threadgroup size {wg[0]}x{wg[1]}x{wg[2]}",
                  f"    public func {k.name}(_ enc: MTLComputeCommandEncoder, {', '.join(args)}) throws {{",
                  f'        enc.setComputePipelineState(try pipeline("{k.name}"))']
        for i, p in enumerate(buffers):
            lines.append(f"        enc.setBuffer({p.name}, offset: 0, index: {i})")
        if scalars:
            inits = ", ".join(f"{p.name}: {p.name}" for p in scalars)
            lines += [f"        var params = ha_params_{k.name}({inits})",
                      f"        enc.setBytes(&params, length: MemoryLayout<ha_params_{k.name}>.stride, "
                      f"index: {len(buffers)})"]
        lines += [f"        enc.dispatchThreadgroups(groups, threadsPerThreadgroup: "
                  f"MTLSize(width: {wg[0]}, height: {wg[1]}, depth: {wg[2]}))",
                  "    }", ""]
        call = ", ".join([f"{p.name}: {p.name}" for p in buffers + scalars] + ["groups: groups"])
        lines += [f"    /// Run kernel {k.name} and wait.",
                  f"    public func {k.name}({', '.join(args)}) throws {{",
                  f"        try run {{ enc in try {k.name}(enc, {call}) }}",
                  "    }", ""]
    lines += ["}", "#endif", ""]
    return "\n".join(lines)


def make_xcframework(tc, out_dir, name, cls, produced, header_text, log):
    """Assemble <cls>Core.xcframework by hand (it is just folders + an Info.plist)."""
    groups = {}
    for tname, path in produced.items():
        if tname.startswith(("ios-", "macos-")) and path.endswith(".a"):
            if tname == "ios-arm64":
                key = ("ios", None)
            elif tname.startswith("ios-sim"):
                key = ("ios", "simulator")
            else:
                key = ("macos", None)
            groups.setdefault(key, []).append((tname, path))
    if not groups:
        return None
    pkg = os.path.join(out_dir, "apple", cls)
    xcf = os.path.join(pkg, f"{cls}Core.xcframework")
    if os.path.exists(xcf):
        shutil.rmtree(xcf)
    libs = []
    lipo = tc.find("llvm-lipo")
    for (platform, variant), items in sorted(groups.items(), key=lambda kv: (kv[0][0], kv[0][1] or "")):
        archs = sorted("arm64" if t.endswith("arm64") else "x86_64" for t, _ in items)
        ident = f"{platform}-{'_'.join(archs)}" + (f"-{variant}" if variant else "")
        d = os.path.join(xcf, ident)
        os.makedirs(os.path.join(d, "Headers"), exist_ok=True)
        dst = os.path.join(d, f"lib{name}.a")
        if len(items) == 1:
            shutil.copyfile(items[0][1], dst)
        else:
            if lipo is None:
                log("  note: llvm-lipo not found; simulator/mac slice has only one architecture")
                shutil.copyfile(items[0][1], dst)
                archs = archs[:1]
            else:
                subprocess.run([lipo, "-create"] + [p for _, p in items] + ["-output", dst], check=True)
        with open(os.path.join(d, "Headers", f"{name}.h"), "w") as f:
            f.write(header_text)
        with open(os.path.join(d, "Headers", "module.modulemap"), "w") as f:
            f.write(f'module {cls}Core {{\n    header "{name}.h"\n    export *\n}}\n')
        entry = {"LibraryIdentifier": ident, "LibraryPath": f"lib{name}.a", "HeadersPath": "Headers",
                 "SupportedArchitectures": archs, "SupportedPlatform": platform}
        if variant:
            entry["SupportedPlatformVariant"] = variant
        libs.append(entry)
    plist = {"AvailableLibraries": libs, "CFBundlePackageType": "XFWK", "XCFrameworkFormatVersion": "1.0"}
    with open(os.path.join(xcf, "Info.plist"), "wb") as f:
        plistlib.dump(plist, f)
    return pkg


def write_swift_package(pkg, prog, src, name, cls):
    platforms = [".iOS(.v15)", ".macOS(.v11)"]
    manifest = f"""// swift-tools-version:5.9
{header_banner(src)}
// Works with Xcode on a Mac, or without a Mac using xtool (github.com/xtool-org/xtool).
import PackageDescription

let package = Package(
    name: "{cls}",
    platforms: [{', '.join(platforms)}],
    products: [.library(name: "{cls}", targets: ["{cls}"])],
    targets: [
        .binaryTarget(name: "{cls}Core", path: "{cls}Core.xcframework"),
        .target(name: "{cls}", dependencies: ["{cls}Core"], path: "Sources/{cls}"),
    ]
)
"""
    with open(os.path.join(pkg, "Package.swift"), "w") as f:
        f.write(manifest)
    sdir = os.path.join(pkg, "Sources", cls)
    os.makedirs(sdir, exist_ok=True)
    with open(os.path.join(sdir, f"{cls}.swift"), "w") as f:
        f.write(render_swift(prog, src, name, cls))


# ====================================================================== Python

def render_python(prog, src, name):
    lines = [f'"""Python bindings for the HA++ library {name} ({src}).', "",
             f"{header_banner(src, '').strip()}", "Pointer arguments accept numpy arrays, ctypes objects,",
             'bytearrays or raw addresses (int)."""', "",
             "import ctypes", "import os", "import platform", "", "",
             "def _find():",
             f'    env = os.environ.get("HAPP_LIB_{name.upper()}")',
             "    if env:",
             "        return env",
             "    here = os.path.dirname(os.path.abspath(__file__))",
             '    arch = "arm64" if platform.machine().lower() in ("arm64", "aarch64") else "x64"',
             "    system = platform.system().lower()",
             '    if system == "windows":',
             f'        rel = f"windows-{{arch}}/{name}.dll"',
             '    elif system == "darwin":',
             f'        rel = f"macos-{{arch}}/lib{name}.dylib"',
             "    else:",
             f'        rel = f"linux-{{arch}}/lib{name}.so"',
             "    return os.path.join(here, os.pardir, rel)", "", "",
             "lib = ctypes.CDLL(_find())", "", "",
             "def ptr(x):",
             '    """Address of numpy arrays / ctypes objects / buffers, for pointer arguments."""',
             "    if x is None:",
             "        return None",
             "    if isinstance(x, int):",
             "        return x",
             '    if hasattr(x, "ctypes"):',
             "        return x.ctypes.data",
             "    if isinstance(x, (ctypes.Array, ctypes.Structure)):",
             "        return ctypes.addressof(x)",
             "    if isinstance(x, bytearray):",
             "        return ctypes.addressof((ctypes.c_char * len(x)).from_buffer(x))",
             "    return ctypes.cast(x, ctypes.c_void_p).value", "", ""]

    def ctype_py(t):
        if t.is_scalar:
            return PY_CTYPE[t.name]
        if t.is_vec:
            return f"({PY_CTYPE[t.elem.name]} * {t.n})"
        if t.is_mat:
            return f"(ctypes.c_float * {t.n * t.n})"
        if t.is_array:
            return f"({ctype_py(t.elem)} * {t.n})"
        if t.is_struct:
            return t.name
        if t.is_ptr:
            return "ctypes.c_void_p"
        raise TypeError(t)

    for st in prog.structs:
        lines.append(f"class {st.name}(ctypes.Structure):")
        fields = ", ".join(f'("{fn}", {ctype_py(ft)})' for fn, ft in st.fields)
        size, _ = T.size_align(st)
        lines += [f"    _fields_ = [{fields}]", "", "",
                  f"assert ctypes.sizeof({st.name}) == {size}, 'HA++ layout mismatch'", "", ""]

    def fn_binding(cname, params, ret):
        argt = ", ".join("ctypes.c_void_p" if t.is_ptr else PY_CTYPE[t.name] for _, t in params)
        rt = "None" if ret.is_void else ("ctypes.c_void_p" if ret.is_ptr else PY_CTYPE[ret.name])
        pnames = [p for p, _ in params]
        call = ", ".join(f"ptr({p})" if t.is_ptr else p for p, t in params)
        return [f"lib.{cname}.argtypes = [{argt}]", f"lib.{cname}.restype = {rt}", "", "",
                f"def {cname}({', '.join(pnames)}):", f"    return lib.{cname}({call})", "", ""]

    for fn in prog.exports:
        lines += fn_binding(fn.name, [(p.name, p.ty) for p in fn.params], fn.ret_ty)
    for k in cpu_kernels(prog):
        params = [(p.name, p.ty) for p in k.params] + [(g, T.U32) for g in ("groups_x", "groups_y", "groups_z")]
        lines += fn_binding(f"{k.name}_cpu", params, T.VOID)
    for k in prog.kernels:
        buffers, scalars = kernel_layout(k)
        if scalars:
            fields = ", ".join(f'("{p.name}", {PY_CTYPE[p.ty.name]})' for p in scalars)
            lines += [f"class ha_params_{k.name}(ctypes.Structure):", f"    _fields_ = [{fields}]", "", ""]
        wg = k.sig["workgroup"]
        lines += [f"{k.name.upper()}_WORKGROUP = ({wg[0]}, {wg[1]}, {wg[2]})",
                  f"{k.name.upper()}_BUFFERS = {len(buffers)}", "", ""]
    return "\n".join(lines).rstrip() + "\n"


# ====================================================================== entry

JS_TYPE = {"i8": "number", "i16": "number", "i32": "number", "u8": "number", "u16": "number", "u32": "number",
           "f32": "number", "f64": "number", "bool": "boolean (0/1)", "i64": "BigInt", "u64": "BigInt"}


def render_js(prog, src, name):
    """ES module that loads <name>.wasm in a browser, a Web Worker or Node, with memory helpers."""
    def js_type(t):
        if t.is_ptr:
            return f"pointer to {t.pointee} (byte offset, number)"
        if t.is_void:
            return "nothing"
        return JS_TYPE.get(str(t), str(t))

    lines = [f"// {name}.mjs: loads {name}.wasm, generated by HA++ from {src}. Don't edit.",
             "// Works in browsers (Safari on iPhone included), Web Workers and Node 18+.",
             "//",
             f'//   import {{ load }} from "./{name}.mjs";',
             f'//   const lib = await load(new URL("./{name}.wasm", import.meta.url));',
             "//   const p = lib.alloc(1024);        // 1024 bytes of the module's memory, 16-byte aligned",
             "//   lib.f32(p, 256).set(values);      // typed-array view of that memory",
             "//   lib.exports.some_function(p, 256);",
             "//",
             "// Pointers are byte offsets into lib.memory; i64/u64 values are BigInt, other numbers are Number.",
             "// Views must be taken again after memory grows (lib.alloc can grow it): don't keep them.",
             ""]
    if prog.exports or prog.cpu_kernels:
        lines.append("// Exported functions:")
        for fn in prog.exports:
            params = ", ".join(f"{p.name}: {js_type(p.ty)}" for p in fn.params)
            lines.append(f"//   {fn.name}({params}) -> {js_type(fn.ret_ty)}")
        for k in prog.cpu_kernels:
            params = ", ".join(f"{p.name}: {js_type(p.ty)}" for p in k.params)
            lines.append(f"//   {k.name}_cpu({params}, groups_x, groups_y, groups_z)  (kernel, run on the CPU)")
        lines.append("")
    sizes, offsets = [], []
    for st in prog.structs:
        if getattr(st, "is_std", False):
            continue
        size, _ = T.size_align(st)
        sizes.append(f"  {st.name}: {size},")
        offs = ", ".join(f"{f}: {o}" for (f, _), o in zip(st.fields, T.field_offsets(st)))
        offsets.append(f"  {st.name}: {{ {offs} }},")
    lines += ["// struct sizes and field offsets in bytes (the same layout as the C header)",
              "export const SIZEOF = {", *sizes, "};", "export const OFFSETOF = {", *offsets, "};", ""]
    lines += [
        "async function bytesOf(source) {",
        "  if (source instanceof ArrayBuffer || ArrayBuffer.isView(source)) return source;",
        "  const url = source instanceof URL ? source : new URL(String(source), globalThis.location?.href);",
        "  if (url.protocol === 'file:') {",
        "    const fs = await import('node:fs/promises');",
        "    return fs.readFile(url);",
        "  }",
        "  const r = await fetch(url);",
        "  if (!r.ok) throw new Error(`can't load ${url}: ${r.status}`);",
        "  return r.arrayBuffer();",
        "}",
        "",
        "/** Instantiate the module. `imports` provides the program's `extern fn` functions. */",
        "export async function load(source, imports = {}) {",
        "  const { instance } = await WebAssembly.instantiate(await bytesOf(source), { env: imports });",
        "  const exports = instance.exports;",
        "  const memory = exports.memory;",
        "  let top = Number(exports.__heap_base.value);",
        "  const align = (x, a) => Math.ceil(x / a) * a;",
        "  top = align(top, 16);",
        "  return {",
        "    exports,",
        "    memory,",
        "    /** Reserve `bytes` in the module's memory (grows it when needed); returns the byte offset. */",
        "    alloc(bytes, alignment = 16) {",
        "      const p = align(top, alignment);",
        "      const end = p + bytes;",
        "      if (end > memory.buffer.byteLength) memory.grow(Math.ceil((end - memory.buffer.byteLength) / 65536));",
        "      top = end;",
        "      return p;",
        "    },",
        "    /** Current end of reserved memory; reset(mark) frees everything reserved after it. */",
        "    mark() { return top; },",
        "    reset(mark) { top = mark; },",
        "    u8: (p, n) => new Uint8Array(memory.buffer, p, n),",
        "    u16: (p, n) => new Uint16Array(memory.buffer, p, n),",
        "    u32: (p, n) => new Uint32Array(memory.buffer, p, n),",
        "    i32: (p, n) => new Int32Array(memory.buffer, p, n),",
        "    f32: (p, n) => new Float32Array(memory.buffer, p, n),",
        "    f64: (p, n) => new Float64Array(memory.buffer, p, n),",
        "  };",
        "}",
        ""]
    return "\n".join(lines)


def write_bridges(prog, out_dir, name, package, cls, targets, produced, tc, metal_src, log,
                  spirv_kernels=(), gpu_runtime=False, src=None):
    src = src or f"{name}.ha"
    files = {}
    has_metal = metal_src is not None and any(t.startswith(("ios", "macos")) for t in targets)
    check_kernel_names(prog)
    header_text = CHeader(prog).render(name, src, set(spirv_kernels), has_metal, gpu_runtime)
    inc = os.path.join(out_dir, "include")
    os.makedirs(inc, exist_ok=True)
    with open(os.path.join(inc, f"{name}.h"), "w") as f:
        f.write(header_text)
    with open(os.path.join(inc, "module.modulemap"), "w") as f:
        f.write(f'module {cls}Core {{\n    header "{name}.h"\n    export *\n}}\n')
    files["header"] = os.path.join(inc, f"{name}.h")
    if gpu_runtime:
        rt = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "runtime", "gpu")
        shutil.copyfile(os.path.join(rt, "ha_gpu.h"), os.path.join(inc, "ha_gpu.h"))

    if any(t.startswith(("android", "linux", "windows")) for t in targets):
        pdir = package.replace(".", "/")
        for lang, render, ext in (("kotlin", render_kotlin, "kt"), ("java", render_java, "java")):
            d = os.path.join(out_dir, "android", lang, pdir)
            os.makedirs(d, exist_ok=True)
            path = os.path.join(d, f"{cls}.{ext}")
            with open(path, "w") as f:
                f.write(render(prog, src, name, package, cls, set(spirv_kernels), gpu_runtime))
            files[lang] = path

    pkg = make_xcframework(tc, out_dir, name, cls, produced, header_text, log)
    if pkg:
        write_swift_package(pkg, prog, src, name, cls)
        files["swift_package"] = pkg
        from .driver import show
        log(f"  built swift package  -> {show(pkg)} ({cls}Core.xcframework, no Xcode used)")

    if any(t.startswith("web") for t in targets):
        wdir = os.path.join(out_dir, "web")
        os.makedirs(wdir, exist_ok=True)
        with open(os.path.join(wdir, f"{name}.mjs"), "w") as f:
            f.write(render_js(prog, src, name))
        files["js"] = os.path.join(wdir, f"{name}.mjs")

    pydir = os.path.join(out_dir, "python")
    os.makedirs(pydir, exist_ok=True)
    with open(os.path.join(pydir, f"{name}.py"), "w") as f:
        f.write(render_python(prog, src, name))
    files["python"] = os.path.join(pydir, f"{name}.py")
    log(f"  built bridges        -> include/{name}.h, Kotlin/Java, Python"
        + (f", web/{name}.mjs" if "js" in files else ""))
    return files
